---
title: "Vitality"
author: "Stefano Coretta"
format: html
---

## Read data

```{r}
#| label: setup

library(HH)
library(tidyverse)
```

```{r}
#| label: polentometro
polentometro_en <- readRDS("data/derived/polentometro_en.rds")

polentometro_page8 <- polentometro_en |> 
  filter(MAXPAGE > 7) |> 
  mutate(
    understand_galloit_birth = ifelse(is.na(understand_galloit_birth), as.character(understand), as.character(understand_galloit_birth)),
    understand_galloit_birth = factor(understand_galloit_birth, levels = c("No, per niente", "Sì, ma molto poco", "Così così", "Sì, lo capisco", "Sì, lo capisco molto bene")),
    speak_galloit_birth = ifelse(is.na(speak_galloit_birth), as.character(speak), as.character(speak_galloit_birth)),
    speak_galloit_birth = factor(speak_galloit_birth, levels = c("No, per niente", "Sì, ma molto poco", "Così così", "Sì, lo parlo bene", "Sì, lo parlo molto bene"))
  )
```

```{r}
#| label: languages
polentometro_page8 |> 
  pivot_longer(c(languages_parents, first_langacq, spoke_to_children, children_speak)) |> 
  drop_na(value) |> 
  filter(
    !(value %in% c("No_minors", "No_adult_children", "Neither")),
  ) |> 
  mutate(
    name = factor(name, levels = c("languages_parents", "first_langacq", "spoke_to_children", "children_speak")),
    value = factor(value, levels = c("Mostly_GI", "Equally", "Mostly_IT"))
  ) |> 
  ggplot(aes(name, fill = value)) +
  geom_bar(position = "fill") +
  theme_dark() +
  scale_fill_brewer(type = "div", palette = "RdBu") +
  labs(
    x = element_blank(), y = "Proportion", fill = "Languages spoken"
  )
```

## Generations

```{r}
#| label: understand-generation
polentometro_page8 |> 
  drop_na(understand_galloit_birth, generation) |> 
  ggplot(aes(generation, fill = understand_galloit_birth)) +
  geom_bar(position = "fill") +
  coord_flip() +
  scale_fill_brewer(type = "div")
```

```{r}
#| label: understand-generation-lik
understand_generation_lik <- polentometro_page8 |> 
  drop_na(understand_galloit_birth, generation) |> 
  select(generation, understand_galloit_birth) |> 
  count(generation, understand_galloit_birth) |> 
  pivot_wider(names_from = understand_galloit_birth, values_from = n) |> 
  mutate(
    across(-generation, ~ifelse(is.na(.x), 0, .x)),
    `Sì, lo capisco bene` = 0
  ) |> 
  relocate(`Sì, lo capisco molto bene`, .after = everything()) |> 
  relocate(`No, per niente`, .after = generation)

likert(
  generation ~ . ,
  understand_generation_lik,
  as.percent = TRUE,
  main = ""
)
```

```{r}
#| label: speak-generation

polentometro_page8 |> 
  drop_na(speak_galloit_birth, generation) |> 
  ggplot(aes(generation, fill = speak_galloit_birth)) +
  geom_bar(position = "fill") +
  coord_flip() +
  scale_fill_brewer(type = "div")
```

```{r}
#| label: speak-generation-lik
speak_generation_lik <- polentometro_page8 |> 
  drop_na(speak_galloit_birth, generation) |> 
  select(generation, speak_galloit_birth) |> 
  count(generation, speak_galloit_birth) |> 
  pivot_wider(names_from = speak_galloit_birth, values_from = n) |> 
  mutate(across(-generation, ~ifelse(is.na(.x), 0, .x))) |> 
  relocate(`Sì, lo parlo molto bene`, .after = everything())

likert(
  generation ~ . ,
  speak_generation_lik,
  as.percent = TRUE,
  main = ""
)
```

```{r}
#| label: languages-generations
polentometro_page8 |> 
  pivot_longer(c(languages_parents, first_langacq, spoke_to_children, children_speak)) |> 
  drop_na(value, generation) |> 
  filter(
    !(value %in% c("No_minors", "No_adult_children", "Neither")),
  ) |> 
  mutate(
    name = factor(name, levels = c("languages_parents", "first_langacq", "spoke_to_children", "children_speak")),
    value = factor(value, levels = c("Mostly_GI", "Equally", "Mostly_IT"))
  ) |> 
  ggplot(aes(name, fill = value)) +
  geom_bar(position = "fill") +
  facet_wrap(~generation) +
  theme_dark() +
  scale_fill_brewer(type = "div", palette = "RdBu") +
  labs(
    x = element_blank(), y = "Proportion", fill = "Languages spoken"
  )
```

## Regions

```{r}
#| label: understand-regions
polentometro_page8 |> 
  drop_na(understand_galloit_birth) |> 
  ggplot(aes(Region, fill = understand_galloit_birth)) +
  geom_bar(position = "fill") +
  coord_flip() +
  scale_fill_brewer(type = "div")
```

```{r}
#| label: speak-regions
polentometro_page8 |> 
  drop_na(speak_galloit_birth) |> 
  ggplot(aes(Region, fill = speak_galloit_birth)) +
  geom_bar(position = "fill") +
  coord_flip() +
  scale_fill_brewer(type = "div")
```

## Areas

```{r}
#| label: understand-areas
polentometro_page8 |> 
  drop_na(understand_galloit_birth) |> 
  ggplot(aes(Area, fill = understand_galloit_birth)) +
  geom_bar(position = "fill") +
  coord_flip() +
  scale_fill_brewer(type = "div")
```

```{r}
#| label: speak-areas
polentometro_page8 |> 
  drop_na(speak_galloit_birth) |> 
  ggplot(aes(Area, fill = speak_galloit_birth)) +
  geom_bar(position = "fill") +
  coord_flip() +
  scale_fill_brewer(type = "div")
```

## Shifts in domains of language use

```{r}
#| label: domains-use

domains_use <- polentometro_page8 |> 
  select(
    CASE, generation, Area, Region,
    starts_with("with_"), starts_with("at_"), starts_with("about_")
  ) |> 
  drop_na(with_tot) |> 
  pivot_longer(with_tot:about_arguments, names_to = "domain")

domains_use_domains <- domains_use |> 
  filter(!str_detect(domain, "tot")) |> 
  mutate(value = as.logical(value))

domains_use_tot <- domains_use |> 
  filter(str_detect(domain, "tot"))
```

```{r}
#| label: domains-with
domains_use_domains |> 
  filter(str_detect(domain, "^with")) |> 
  ggplot(aes(domain, fill = value)) +
  geom_bar(position = "fill") +
  coord_flip()

domains_use_domains |> 
  filter(str_detect(domain, "^with")) |> 
  ggplot(aes(domain, fill = value)) +
  geom_bar(position = "fill") +
  coord_flip() +
  facet_wrap(~generation)

domains_use_domains |> 
  filter(str_detect(domain, "^with")) |> 
  ggplot(aes(domain, fill = value)) +
  geom_bar(position = "fill") +
  coord_flip() +
  facet_wrap(~Region)
```

```{r}
#| label: domains-at
domains_use_domains |> 
  filter(str_detect(domain, "^at")) |> 
  ggplot(aes(domain, fill = value)) +
  geom_bar(position = "fill") +
  coord_flip()

domains_use_domains |> 
  filter(str_detect(domain, "^at")) |> 
  ggplot(aes(domain, fill = value)) +
  geom_bar(position = "fill") +
  coord_flip() +
  facet_wrap(~generation)

domains_use_domains |> 
  filter(str_detect(domain, "^at")) |> 
  ggplot(aes(domain, fill = value)) +
  geom_bar(position = "fill") +
  coord_flip() +
  facet_wrap(~Region)
```

```{r}
#| label: domains-about
domains_use_domains |> 
  filter(str_detect(domain, "^about")) |> 
  ggplot(aes(domain, fill = value)) +
  geom_bar(position = "fill") +
  coord_flip()

domains_use_domains |> 
  filter(str_detect(domain, "^about")) |> 
  ggplot(aes(domain, fill = value)) +
  geom_bar(position = "fill") +
  coord_flip() +
  facet_wrap(~generation)

domains_use_domains |> 
  filter(str_detect(domain, "^about")) |> 
  ggplot(aes(domain, fill = value)) +
  geom_bar(position = "fill") +
  coord_flip() +
  facet_wrap(~Region)
```

