---
title: "Untitled"
format: html
---

```{r}
#| label: setup

library(tidyverse)
```

```{r}
#| label: read-data

polentometro_en <- readRDS("data/derived/polentometro_en.rds")
```


```{r}
translation <- polentometro_en |> 
  select(translation, Region, Province, Comune) |> 
  drop_na(translation) |> 
  arrange(Region, Province, Comune)

write_csv(translation, "data/derived/translation.csv")
```

```{r}
translation_boom_sempre <- polentometro_en |> 
  filter(
    speak_frequency == "Lo parlo sempre",
    generation %in% c("Boomers", "Silent")
  ) |> 
  select(translation, Region, Province, Comune, speak_galloit_birth) |> 
  drop_na(translation) |> 
  arrange(Region, Province, speak_galloit_birth, Comune)

translation_boom_molto_bene <- polentometro_en |> 
  filter(
    speak_galloit_birth == "Sì, lo parlo molto bene",
    generation %in% c("Boomers", "Silent")
  ) |> 
  select(translation, Region, Province, Comune, speak_galloit_birth) |> 
  drop_na(translation) |> 
  arrange(Region, Province, speak_galloit_birth, Comune)

write_csv(translation_boom_molto_bene, "data/derived/translation_boom_molto_bene.csv")
```

