---
title: "07_attitude"
author: "Stefano Coretta"
format: html
---

## Setup

```{r}
#| label: setup
#| include: false

library(HH)
library(tidyverse)
library(brms)

```

## Job sector

```{r}
polentometro_job <- readRDS("data/derived/polentometro.rds") |> 
  drop_na(educated, job_sector) |> 
  select(CASE, educated:urban, job_5) |> 
  mutate(
    across(educated:urban, as.ordered),
    job_5 = factor(job_5, levels = c("Primary", "Secondary", "Tertiary", "Quaternary", "Quinary")),
    job_5_num = as.integer(job_5)
  )
```

```{r}
job_lik <- polentometro_job |> 
  select(job_5, educated:urban) |> 
  pivot_longer(educated:urban) |> 
  count(job_5, name, value) |> 
  group_by(job_5, name) |> 
  pivot_wider(names_from = value, values_from = n) |> 
  mutate(
    across(everything(), ~ifelse(is.na(.x), 0, .x))
  ) |> 
  relocate(`1`, `2`, .before = `3`) |> 
  select(-`NA`)
```

```{r}
for (sector in levels(job_lik$job_5)) {
  plot(likert(
    name ~ . ,
    job_lik |> filter(job_5 == sector),
    as.percent = TRUE,
    main = sector,
    xlimEqualLeftRight = TRUE
  ))
}
```

```{r}
for (sector in levels(job_lik$job_5)) {
  plot(likert(
    name ~ . ,
    job_lik |> filter(job_5 == sector) |> select(-`4`),
    as.percent = TRUE,
    main = sector,
    xlimEqualLeftRight = TRUE
  ))
}
```


```{r}
job_bm <- brm(
  mvbind(educated, friendly, funny, kind, modern, refined, rich, urban) ~ mo(job_5_num),
  data = polentometro_job,
  family = cumulative(link = "probit"),
  cores = 4,
  seed = 9123,
  file = "data/cache/job_bm"
)
```

```{r}
summary(job_bm)
```

```{r}
plot(conditional_effects(job_bm, categorical = TRUE), ask = FALSE)
```

## Study subject

```{r}
polentometro_study <- readRDS("data/derived/polentometro.rds") |> 
  drop_na(educated, study_sector) |> 
  select(CASE, educated:urban, study_sector, study_subject)
```

```{r}
study_lik <- polentometro_study |> 
  select(study_subject, educated:urban) |> 
  pivot_longer(educated:urban) |> 
  count(study_subject, name, value) |> 
  group_by(study_subject, name) |> 
  pivot_wider(names_from = value, values_from = n) |> 
  mutate(
    across(everything(), ~ifelse(is.na(.x), 0, .x))
  ) |> 
  relocate(`1`, `2`, .before = `3`)
```

```{r}
for (subject in unique(study_lik$study_subject)) {
  plot(likert(
    name ~ . ,
    study_lik |> filter(study_subject == subject),
    as.percent = TRUE,
    main = subject,
    xlimEqualLeftRight = TRUE
  ))
}
```

```{r}
for (subject in unique(study_lik$study_subject)) {
  plot(likert(
    name ~ . ,
    study_lik |> filter(study_subject == subject) |> select(-`4`),
    as.percent = TRUE,
    main = subject,
    xlimEqualLeftRight = TRUE
  ))
}
```

