name: "Set todo's and discussions to Action board"
on:
  issues:
    types: [labeled]

jobs:
  assign-project:
    name: Set project to Action board
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.labels.*.name, 'todo') ||
          contains(github.event.issue.labels.*.name, 'discussion')
        with:
          project: 'https://github.com/stefanocoretta/lombard-vitality/projects/1'
          column_name: 'Assigned'
